### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by NixerSo5** [ChatGPTNextWeb/ChatGPT-Next-Web#4350]
### Bug Description

$ next dev
[Next] build mode standalone
[Next] build with chunk:  true
[Next] build mode standalone
[Next] build with chunk:  true
npm WARN invalid config proxy=true set in environment
npm WARN invalid config Must be full url with "http://"
 ⚠ Found lockfile missing swc dependencies, patching...
npm WARN invalid config proxy=true set in environment
npm WARN invalid config Must be full url with "http://"
 ⨯ Failed to patch lockfile, please try uninstalling and reinstalling next in this workspace
TypeError: fetch failed
    at node:internal/deps/undici/undici:12345:11
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async fetchPkgInfo (D:\mysdk\maoyou\ChatGPT-Next-Web\node_modules\next\dist\lib\patch-incorrect-lockfile.js:65:17)
    at async Promise.all (index 1)
    at async patchIncorrectLockfile (D:\mysdk\maoyou\ChatGPT-Next-Web\node_modules\next\dist\lib\patch-incorrect-lockfile.js:161:26) {
  cause: Error: certificate has expired
      at TLSSocket.onConnectSecure (node:_tls_wrap:1674:34)
      at TLSSocket.emit (node:events:518:28)
      at TLSSocket._finishInit (node:_tls_wrap:1085:8)
      at ssl.onhandshakedone (node:_tls_wrap:871:12) {
    code: 'CERT_HAS_EXPIRED'
  }
}

### Steps to Reproduce

1 .env   set   PROXY_URL=http://localhost:7890
2 yarn dev

### Expected Behavior

when i  want use proxy setting      and  run dev
it  show this error  
and  proxy not work

### Deployment Method

- [ ] Docker
- [ ] Vercel
- [X] Server

### Desktop OS

windows11

### Desktop Browser

edge

### Desktop Browser Version

123.0.2420.41

**Comment by fred-bf** [comment]
please check you local certification as what error logs mentioned
