### ISSUE TITLE
[Bug] 数据同步设置里面webdav不能正常使用

### ISSUE THREAD

**Issue by FINatiend** [ChatGPTNextWeb/ChatGPT-Next-Web#4532]
### Bug Description

如题，使用坚果云webDAV服务不能正常使用。

### Steps to Reproduce

1. 点击检查可用性按钮时，会显示不可用，并且返回check 520，post链接里会自动加上ChatGPTNextWeb字段。

<img width="577" alt="iShot_2024-04-17_11 05 24" src="https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/37405653/1794cc2a-a1c5-4aed-9003-b387b84ecba5">

2. 点击同步按钮，会出现下面的错误Unexpected token 'e', "error code: 520" is not valid JSON

![ztfk9wp2](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/37405653/f41c3148-90f1-4b8e-94f7-cd246e575473)

3. 下图是坚果云webdav服务，是正常开启的

![fvye49wd](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/37405653/946166b2-3bd7-4263-8186-7f80e6549c67)

4. 在另外一款文献管理软件zotero中，坚果云webdav也是也可以正常使用的，该链接结尾是以/zotero/结尾的

![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/37405653/76ab3ea1-0b11-490f-8ca2-6a9dab3add14)

5.坚果云的文件也创建了
<img width="958" alt="image" src="https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/37405653/7434cc67-bacf-4c59-a9d3-080e3bf91cf5">

### Expected Behavior

坚果云webdav服务正常使用

### Deployment Method

- [ ] Docker
- [ ] Vercel
- [ ] Server

### Desktop OS

mac os 13

### Desktop Browser

chrome

**Comment by zhibisora** [comment]
我有同样的问题

**Comment by Dean-YZG** [comment]
请问使用的是最新版本么？最新版本中已经将/api/cors接口迁移到了/api/webdav，并增加了基于安全方面考量的一些设计

**Comment by hexsix** [comment]
> 请问使用的是最新版本么？最新版本中已经将/api/cors接口迁移到了/api/webdav，并增加了基于安全方面考量的一些设计

@Dean-YZG 是的，最新版本。 我部署了 PR #4525 之后遇到了 Json 解析错误的 BUG。

<details>

<summary>Logs</summary>

```
page-df770995f097e59f.js:1 [Config] got config from build time {version: 'v2.11.3', commitDate: '1713250762000', commitHash: '9b2cb1e1c3252298c8a94fb195af683ac7aea5e9', buildMode: 'standalone', isApp: false}
serviceWorkerRegister.js:4 ServiceWorker registration successful with scope:  https://exmaple.com/
670.3f8d4b1ccea09673.js:1 [Update] local version  v2.11.3
670.3f8d4b1ccea09673.js:1 [Update] remote version  v2.11.3
page-df770995f097e59f.js:1 [Config] got config from server {needCode: true, hideUserApiKey: false, disableGPT4: false, hideBalanceQuery: true, disableFastLink: false, …}
page-df770995f097e59f.js:1 
        
        
       GET https://example.com/api/webdav/chatgpt-next-web/backup.json?endpoint=https://dav.jianguoyun.com/dav/ 520
get @ page-df770995f097e59f.js:1
sync @ page-df770995f097e59f.js:1
onClick @ 670.3f8d4b1ccea09673.js:1
l5 @ bce60fc1-e55b90606913faf1.js:9
ar @ bce60fc1-e55b90606913faf1.js:9
(anonymous) @ bce60fc1-e55b90606913faf1.js:9
u2 @ bce60fc1-e55b90606913faf1.js:9
u3 @ bce60fc1-e55b90606913faf1.js:9
(anonymous) @ bce60fc1-e55b90606913faf1.js:9
oS @ bce60fc1-e55b90606913faf1.js:9
ir @ bce60fc1-e55b90606913faf1.js:9
u9 @ bce60fc1-e55b90606913faf1.js:9
i6 @ bce60fc1-e55b90606913faf1.js:9
i4 @ bce60fc1-e55b90606913faf1.js:9
page-df770995f097e59f.js:1 [WebDav] get key =  account_name@jianguoyun.com 520 
page-df770995f097e59f.js:1 [Sync] failed to get remote state SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON
    at JSON.parse (<anonymous>)
    at Object.sync (page-df770995f097e59f.js:1:247469)
    at async onClick (670.3f8d4b1ccea09673.js:1:16330)
7698-bb5d18468650f39a.js:1 [Sync] SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON
    at JSON.parse (<anonymous>)
    at Object.sync (page-df770995f097e59f.js:1:247469)
    at async onClick (670.3f8d4b1ccea09673.js:1:16330)
window.console.error @ 7698-bb5d18468650f39a.js:1
onClick @ 670.3f8d4b1ccea09673.js:1
await in onClick (async)
l5 @ bce60fc1-e55b90606913faf1.js:9
ar @ bce60fc1-e55b90606913faf1.js:9
(anonymous) @ bce60fc1-e55b90606913faf1.js:9
u2 @ bce60fc1-e55b90606913faf1.js:9
u3 @ bce60fc1-e55b90606913faf1.js:9
(anonymous) @ bce60fc1-e55b90606913faf1.js:9
oS @ bce60fc1-e55b90606913faf1.js:9
ir @ bce60fc1-e55b90606913faf1.js:9
u9 @ bce60fc1-e55b90606913faf1.js:9
i6 @ bce60fc1-e55b90606913faf1.js:9
i4 @ bce60fc1-e55b90606913faf1.js:9
```

</details>

**Comment by ipez** [comment]
同样的问题

**Comment by led-ury** [comment]
same question

**Comment by ldw1216** [comment]
一样的问题

**Comment by daiaji** [comment]
代理地址为空，WebDAV 地址为'https://dav.jianguoyun.com/dav/'时，同步可用，但检查可用性报错。
![屏幕截图_20240523_192527](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/25875791/dac9acd8-092a-49e1-a35b-4566047248ca)

**Comment by TheToiletsWar** [comment]
same question,anyone pepole solved this problem?

**Comment by Sligcm** [comment]
这么大的 BUG，作者为什么不回复呢？

**Comment by wyx1818** [comment]
@Dean-YZG 

> 请问使用的是最新版本么？最新版本中已经将/api/cors接口迁移到了/api/webdav，并增加了基于安全方面考量的一些设计

能帮忙看下么，现在还是不可用状态

**Comment by cmx-ops** [comment]
> 代理地址为空，WebDAV 地址为`https://dav.jianguoyun.com/dav/`时，同步可用，但检查可用性报错。 ![屏幕截图_20240523_192527](https://private-user-images.githubusercontent.com/25875791/333163309-dac9acd8-092a-49e1-a35b-4566047248ca.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzNDcwOTMsIm5iZiI6MTcxODM0Njc5MywicGF0aCI6Ii8yNTg3NTc5MS8zMzMxNjMzMDktZGFjOWFjZDgtMDkyYS00OWUxLWEzNWItNDU2NjA0NzI0OGNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE0VDA2MzMxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIxYTg0ZWVhZmJmZjIzOTNmYmM0MTgzOWVlMzcwYTZjYzJiODY0NmU1NzA3N2NlYzljOTIyZmY4NzI2ZGVmNzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.j5WKDNjX7ud_5eE72OVAWLel-K4tsEEFvYnREPwGanU)

你用的哪个版本的

**Comment by OliverZhangGit** [comment]
解决了吗？

**Comment by YichenWei0601** [comment]
Same problem now!

**Comment by FINatiend** [comment]
您的来件已收到--FINatiend
