### ISSUE TITLE
[Bug] invalid_request_error with claude and anthropic api

### ISSUE THREAD

**Issue by MelBourbon** [ChatGPTNextWeb/ChatGPT-Next-Web#5256]
### 📦 Deployment Method

Docker

### 📌 Version

2.14.1

### 💻 Operating System

Ubuntu

### 📌 System Version

22.04

### 🌐 Browser

Chrome

### 📌 Browser Version

127.0.6533.100

### 🐛 Bug Description

I added my claude (anthopic) API Key to `docker-compose.yml` with `ANTHROPIC_API_KEY: xxx
`
Docker starts fine but when sending prompt the following error is received.

```
{
  "type": "error",
  "error": {
    "type": "invalid_request_error",
    "message": "messages.1.content: all 'assistant' content blocks should be text"
  }
}
```
If I add `ANTHROPIC_API_VERSION: 2023-06-01` to `docker-compose.yml `the docker does not start with following error:

```
Traceback (most recent call last):
  File "/usr/bin/docker-compose", line 33, in <module>
    sys.exit(load_entry_point('docker-compose==1.29.2', 'console_scripts', 'docker-compose')())
  File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 81, in main
    command_func()
  File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 200, in perform_command
    project = project_from_options('.', options)
  File "/usr/lib/python3/dist-packages/compose/cli/command.py", line 60, in project_from_options
    return get_project(
  File "/usr/lib/python3/dist-packages/compose/cli/command.py", line 148, in get_project
    config_data = config.load(config_details, interpolate)
  File "/usr/lib/python3/dist-packages/compose/config/config.py", line 423, in load
    processed_files = [
  File "/usr/lib/python3/dist-packages/compose/config/config.py", line 424, in <listcomp>
    process_config_file(config_file, config_details.environment, interpolate=interpolate)
  File "/usr/lib/python3/dist-packages/compose/config/config.py", line 626, in process_config_file
    validate_against_config_schema(config_file, config_file.version)
  File "/usr/lib/python3/dist-packages/compose/config/validation.py", line 474, in validate_against_config_schema
    handle_errors(
  File "/usr/lib/python3/dist-packages/compose/config/validation.py", line 541, in handle_errors
    error_msg = '\n'.join(format_error_func(error) for error in errors)
  File "/usr/lib/python3/dist-packages/compose/config/validation.py", line 541, in <genexpr>
    error_msg = '\n'.join(format_error_func(error) for error in errors)
  File "/usr/lib/python3/dist-packages/compose/config/validation.py", line 450, in process_config_schema_errors
    return handle_generic_error(error, path)
  File "/usr/lib/python3/dist-packages/compose/config/validation.py", line 320, in handle_generic_error
    config_key, error_msg = _parse_oneof_validator(error)
  File "/usr/lib/python3/dist-packages/compose/config/validation.py", line 411, in _parse_oneof_validator
    json.dumps(context.instance),
  File "/usr/lib/python3.10/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.10/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.10/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.10/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
```

### 📷 Recurrence Steps

1. Set up docker-compose.yml
2. Start docker
3. Set model to claude
4. Sending prompt

### 🚦 Expected Behavior

Model should reply

**Comment by MelBourbon** [comment]
> Please follow the [issue template](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/blob/main/.github/ISSUE_TEMPLATE/bug_report.md) to update description of your issue.

Issue Template not existing anymore

**Comment by lloydzhou** [comment]
这个项目是js的，但是看给出来的一堆错误日志是python的？
