### ISSUE TITLE
[Bug] Error when using o1-preview large models

### ISSUE THREAD

**Issue by 1-bytes** [ChatGPTNextWeb/ChatGPT-Next-Web#5423]
### 📦 Deployment Method

Docker

### 📌 Version

2.15.2

### 💻 Operating System

Windows, macOS, Ubuntu, iOS, iPad OS, Android

### 📌 System Version

14.6.1 (23G93)

### 🌐 Browser

Chrome

### 📌 Browser Version

128.0.6613.120（正式版本） (arm64)

### 🐛 Bug Description

The following error was prompted when using the o1-preview big model:

`{
  "error": true,
  "message": "The string did not match the expected pattern."
}
`

The docker startup command is as follows:

```
docker stop chatgpt

docker rm -f chatgpt

docker pull yidadaa/chatgpt-next-web

docker run -d -p 9001:3000 \
   -e HIDE_USER_API_KEY=1 \
   -e BASE_URL=https://apic.ohmygpt.com/ \
   -e OPENAI_API_KEY=sk-xxxxxxxxx \
   -e ANTHROPIC_API_KEY=sk-xxxxxxxxx \
   -e CODE=xxxxxxxxxx \
   -e CUSTOM_MODELS=-all,+o1-preview=o1-preview,+chatgpt-4o-latest,+claude-3-5-sonnet,+dall-e-3 \
   -e DEFAULT_MODEL=o1-preview \
   --name chatgpt \
   yidadaa/chatgpt-next-web
```

### 🚦 Expected Behavior

success

### 📝 Additional Information

The backend api uses the ohmygpt service: https://www.ohmygpt.com

**Comment by Dogtiti** [comment]
@lloydzhou docker image 还没更新把

**Comment by lloydzhou** [comment]
![image](https://github.com/user-attachments/assets/8dbac592-6aae-438b-9a94-4e1bb5eb36df)

**Comment by zhanghaotian2018** [comment]
yarn 是报错

yarn run v1.22.22
node: v20.13.1
NAME="CentOS Linux" VERSION="8 (Core)"



ypeError: Failed to parse URL from ./prompts.json
    at new Request (node:internal/deps/undici/undici:4855:19)
    at i (/data/workspace/ChatGPT-Next-Web/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:177224)
    ... 2 lines matching cause stack trace ...
    at async globalThis.fetch (/data/workspace/ChatGPT-Next-Web/.next/server/chunks/712.js:11:131378) {
  [cause]: TypeError: Invalid URL
      at new URL (node:internal/url:797:36)
      at new Request (node:internal/deps/undici/undici:4853:25)
      at i (/data/workspace/ChatGPT-Next-Web/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:177224)
      at k (/data/workspace/ChatGPT-Next-Web/.next/server/chunks/712.js:11:134634)
      at /data/workspace/ChatGPT-Next-Web/.next/server/chunks/712.js:11:136783
      at async globalThis.fetch (/data/workspace/ChatGPT-Next-Web/.next/server/chunks/712.js:11:131378) {
    code: 'ERR_INVALID_URL',
    input: './prompts.json'
  }
